site_name: Rohan blog
nav:
  - Home: index.md
  - 2025:
    - Overzicht 2025: 2025/index.md
    - Wandeling De Buitenlanden Beverwijk: 2025/2025-02-26-wandeling-buitenlanden-beverwijk.md
  - 2019:
    - Overzicht 2019: 2019/index.md
    - Disneyland Parijs: 2019/2019-08-08-disneyland-parijs.md
  - 2018:
    - Overzicht 2018: 2018/index.md
    - Vakantie Griekenland: 2018/2018-07-vakantie-griekenland.md
    - Gouden momenten bij Lichtfabriek Haarlem: 2018/2018-07-24-shoot-lichtfabriek-haarlem.md
    - Lancia meeting dag: 2018/2018-09-09-lancia-dag.md
  - Over mij: over-mij.md
  - Contact: contact.md
theme:
  name: terminal
  custom_dir: overrides