site_name: Rohan blog
site_author: Rohan van Wijk
site_description: Rohan's blog website
site_url: https://blog.rohanvanwijk.nl
nav:
  - Home: index.md
  - 2025:
      - Overzicht 2025: 2025/index.md
      - Web Animaties: 2025/2025-05-10-web-animaties.md
      - Mijn Favoriete Muziek: 2025/2025-04-21-muziek.md
      - Wandeling in 't Wed Bloemendaal: 2025/2025-04-26_wandeling-wed-bloemendaal.md
      - Bezoek aan Autoclassiqa: 2025/2025-04-19-autoclassiqa.md
      - Onze autoshoot op een zonnige ochtend: 2025/2025-03-16-automotive-shoot.md
      - Wandeling De Buitenlanden Beverwijk: 2025/2025-02-26-wandeling-buitenlanden-beverwijk.md
  - 2020:
      - Overzicht 2020: 2020/index.md
      - Kerstmagie in Maastricht: 2020/2020-12-21-kerst-maastricht.md
      - Supercar Sunday Zandvoort: 2020/2020-09-20-supercarsunday-zandvoort.md
      - Vliegtuig spotten op Texel: 2020/2020-06-20-texel-vliegveld.md
  - 2019:
      - Overzicht 2019: 2019/index.md
      - Onze Gezellige Familievakantie bij Green Resort Mooi Bemelen: 2019/2019-12-19-bemelen.md
      - Wandelen in Landgoed Koningshof: 2019/2019-09-12-koningshof.md
      - Parijs vanaf de Top: 2019/2019-08-10-parijs.md
      - Disneyland Parijs: 2019/2019-08-08-disneyland-parijs.md
  - 2018:
      - Overzicht 2018: 2018/index.md
      - Lancia meeting dag: 2018/2018-09-09-lancia-dag.md
      - Gouden momenten bij Lichtfabriek Haarlem: 2018/2018-07-24-shoot-lichtfabriek-haarlem.md
      - Vakantie Griekenland: 2018/2018-07-vakantie-griekenland.md
  - Over mij: over-mij.md
  - Contact: contact.md
  - Sitemap: sitemap.xml
theme:
  name: terminal
  custom_dir: overrides
